ALTER TABLE `laborutkm`.`applicant` 
CHANGE COLUMN `DateCreated` `DateCreated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ;

ALTER TABLE `laborutkm`.`company` 
CHANGE COLUMN `DateCreated` `DateCreated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ;

ALTER TABLE `laborutkm`.`evaluation` 
CHANGE COLUMN `DateCreated` `DateCreated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ;

ALTER TABLE `laborutkm`.`joboffer` 
CHANGE COLUMN `DateCreated` `DateCreated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ;

ALTER TABLE `laborutkm`.`companyroledtoes` 
CHANGE COLUMN `DateCreated` `DateCreated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ;

ALTER TABLE `laborutkm`.`person` 
CHANGE COLUMN `DateCreated` `DateCreated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ;

ALTER TABLE `laborutkm`.`recruitmentprocessstepdtoes` 
CHANGE COLUMN `DateCreated` `DateCreated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ;

ALTER TABLE `laborutkm`.`role` 
CHANGE COLUMN `DateCreated` `DateCreated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ;

ALTER TABLE `laborutkm`.`section` 
CHANGE COLUMN `DateCreated` `DateCreated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ;

ALTER TABLE `laborutkm`.`employee` 
CHANGE COLUMN `DateCreated` `DateCreated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ;
