//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboruTKM.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CompanyResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompanyResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaboruTKM.Web.Resources.CompanyResource", typeof(CompanyResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procesos activos.
        /// </summary>
        internal static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Candidatos en proceso.
        /// </summary>
        internal static string activeApplicants {
            get {
                return ResourceManager.GetString("activeApplicants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adicionar candidato.
        /// </summary>
        internal static string addApplicant {
            get {
                return ResourceManager.GetString("addApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adicionar cargo.
        /// </summary>
        internal static string addJobOpening {
            get {
                return ResourceManager.GetString("addJobOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Candidatos con alerta.
        /// </summary>
        internal static string alertApplicants {
            get {
                return ResourceManager.GetString("alertApplicants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Candidatos.
        /// </summary>
        internal static string applicants {
            get {
                return ResourceManager.GetString("applicants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procesos Finalizados.
        /// </summary>
        internal static string done {
            get {
                return ResourceManager.GetString("done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargos disponibles.
        /// </summary>
        internal static string jobOpenings {
            get {
                return ResourceManager.GetString("jobOpenings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empleados.
        /// </summary>
        internal static string myEmployees {
            get {
                return ResourceManager.GetString("myEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Candidatos en pausa.
        /// </summary>
        internal static string pausedApplicants {
            get {
                return ResourceManager.GetString("pausedApplicants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reclutamiento.
        /// </summary>
        internal static string recruitment {
            get {
                return ResourceManager.GetString("recruitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle de los procesos de selección.
        /// </summary>
        internal static string recruitmentDetails {
            get {
                return ResourceManager.GetString("recruitmentDetails", resourceCulture);
            }
        }
    }
}
